window.QUESTIONS = [
  {id:1,chapter:1,chapterTitle:"👀 第一章：认一认",title:"爷爷的朋友",sceneType:"q1",dialogue:["爷爷：“小乐，这是爷爷的朋友，林爷爷。”"],question:"小乐应该怎样打招呼？",options:[{id:"a",text:"👋 “林爷爷，您好！”"},{id:"b",text:"📢 “喂，你好！”"},{id:"c",text:"😶 什么都不说"}],correctAnswer:"a",feedback:["⭐ 见到尊长，要有礼貌地称呼。"],resolution:["小乐微笑着向林爷爷问好。"],learningText:"称尊长。"},
  {id:2,chapter:1,chapterTitle:"👀 第一章：认一认",title:"妈妈的朋友",sceneType:"q2",dialogue:["妈妈：“小乐，这是王阿姨。”"],question:"小乐应该怎样说？",options:[{id:"a",text:"🙂 “王阿姨，您好！”"},{id:"b",text:"😎 “王美玲，你好！”"},{id:"c",text:"👋 “喂！”"}],correctAnswer:"a",feedback:["⭐ 知道长辈的名字，也要使用合适的尊称。"],resolution:["王阿姨开心地回应小乐的问候。"],seniorPrompt:"💭 为什么妈妈可以叫朋友的名字，小乐却应该称她“王阿姨”？"},
  {id:3,chapter:1,chapterTitle:"👀 第一章：认一认",title:"我不知道怎么称呼",sceneType:"q3",dialogue:["小乐：“我不知道要叫这位长辈什么……”"],question:"小乐应该怎么办？",options:[{id:"a",text:"🤐 假装没看到"},{id:"b",text:"📢 随便叫一个名字"},{id:"c",text:"🙋 问爸爸妈妈：“请问我应该怎样称呼这位长辈？”"}],correctAnswer:"c",feedback:["⭐ 不知道称呼时，可以有礼貌地请教大人。"],resolution:["小乐先请教大人，再有礼貌地向长辈问好。"]},
  {id:4,chapter:2,chapterTitle:"🙋 第二章：称一称",title:"知道叔叔的名字",sceneType:"q4",dialogue:["小乐知道叔叔的名字叫“陈志明”。"],question:"见到叔叔时，小乐应该怎么说？",options:[{id:"a",text:"📢 “陈志明！你来啦！”"},{id:"b",text:"🙂 “陈叔叔，您好！”"},{id:"c",text:"👋 “喂！”"}],correctAnswer:"b",feedback:["⭐ 知道尊长的名字，也不直接用名字称呼。"],resolution:["小乐有礼貌地向陈叔叔问好。"],learningText:"称尊长，勿呼名。"},
  {id:5,chapter:2,chapterTitle:"🙋 第二章：称一称",title:"同学告诉我老师的名字",sceneType:"q5",dialogue:["同学：“我知道老师的全名！”","第二天，小乐见到了老师。"],question:"小乐应该怎样称呼？",options:[{id:"a",text:"📢 直接叫老师的全名"},{id:"b",text:"🙋 “老师，您好！”"},{id:"c",text:"😆 学同学给老师取外号"}],correctAnswer:"b",feedback:["⭐ 知道老师的姓名，不代表应该直接用姓名称呼老师。"],resolution:["小乐礼貌地说：“老师，您好！”"],seniorPrompt:"💭 知道一个人的名字，和怎样称呼一个人，是同一件事吗？"},
  {id:6,chapter:2,chapterTitle:"🙋 第二章：称一称",title:"大人都这样叫",sceneType:"q6",dialogue:["爸爸对一位长辈说：“建国，好久不见！”","小乐：“爸爸这样叫，我也可以吗？”"],question:"小乐应该怎么办？",options:[{id:"a",text:"😎 跟爸爸一样叫“建国”"},{id:"b",text:"🙋 先问爸爸：“我应该怎样称呼这位长辈？”"},{id:"c",text:"📢 随便叫一个称呼"}],correctAnswer:"b",feedback:["⭐ 大人之间的称呼，不一定适合小朋友跟着使用。"],resolution:["小乐先请教爸爸，再用合适的称呼问好。"]},
  {id:7,chapter:3,chapterTitle:"🌱 第三章：谦一谦",title:"爷爷不会用手机",sceneType:"q7",dialogue:["爷爷不会把手机字体调大。","小乐很快就会操作。"],question:"小乐应该怎样说？",options:[{id:"a",text:"😏 “这么简单你都不会？”"},{id:"b",text:"📢 “看吧！还是我最厉害！”"},{id:"c",text:"🙂 “爷爷，我来帮您调大一点。”"}],correctAnswer:"c",feedback:["⭐ 有本领，可以用来帮助别人，不需要炫耀。"],resolution:["小乐耐心地帮爷爷把字体调大。"],learningText:"对尊长，勿见能。"},
  {id:8,chapter:3,chapterTitle:"🌱 第三章：谦一谦",title:"奶奶算错了",sceneType:"q8",dialogue:["奶奶在算东西时，不小心算错了。","小乐发现了。"],question:"小乐应该怎样说？",options:[{id:"a",text:"😂 “哈哈！奶奶也会算错！”"},{id:"b",text:"📢 马上叫大家来看"},{id:"c",text:"🙂 “奶奶，我们要不要再算一次看看？”"}],correctAnswer:"c",feedback:["❤️ 发现别人做错，不需要让别人难堪。"],resolution:["小乐温和地陪奶奶再算一次。"],seniorPrompt:"💭 指出错误和炫耀自己，有什么不同？"},
  {id:9,chapter:3,chapterTitle:"🌱 第三章：谦一谦",title:"长辈称赞小乐",sceneType:"q9",dialogue:["长辈：“小乐，你这次比赛表现得很好！”"],question:"小乐应该怎样回应？",options:[{id:"a",text:"😎 “当然啦！这里没有人比我厉害！”"},{id:"b",text:"🙂 “谢谢您的鼓励，我还会继续学习。”"},{id:"c",text:"😂 “其他人都比不上我！”"}],correctAnswer:"b",feedback:["⭐ 做得好，可以开心；受到称赞，也可以保持谦虚。"],resolution:["小乐感谢长辈的鼓励，并继续认真学习。"]},
  {id:10,chapter:4,chapterTitle:"🤝 全班共同任务",title:"新来的老师",sceneType:"q10",dialogue:["小乐知道新老师的全名叫“李慧敏”。","这是他们第一次见面。"],question:"小乐应该怎么说？",options:[{id:"a",text:"📢 “李慧敏，你好！”"},{id:"b",text:"🙋 “李老师，您好！”"},{id:"c",text:"😆 直接给老师取外号"}],correctAnswer:"b",feedback:["⭐ 尊重师长，使用合适的称呼。"],resolution:["小乐有礼貌地向李老师问好。"],learningText:"称尊长，勿呼名。"},
  {id:11,chapter:4,chapterTitle:"🤝 全班共同任务",title:"外婆不会使用平板电脑",sceneType:"q11",dialogue:["外婆不会打开一个应用程序。","小乐很熟练。"],question:"小乐应该怎样做？",options:[{id:"a",text:"😏 “我早就会了，你怎么还不会？”"},{id:"b",text:"🙂 “外婆，我慢慢教您。”"},{id:"c",text:"📢 把其他人叫来看外婆不会用"}],correctAnswer:"b",feedback:["⭐ 真正的本领，不是用来炫耀，而是用来帮助别人。"],resolution:["小乐一步一步耐心地教外婆。"],learningText:"对尊长，勿见能。"},
  {id:12,chapter:4,chapterTitle:"🤝 全班共同任务",title:"称呼与帮助",sceneType:"q12",dialogue:["妈妈：“这是妈妈的老师，张老师。”","后来，张老师不会使用手机里的一个功能，而小乐刚好会。"],question:"小乐应该怎么做？",options:[{id:"a",text:"😎 “张美华，这个我都会，你怎么不会？”"},{id:"b",text:"😶 什么都不说，也不帮忙"},{id:"c",text:"🙂 “张老师，您好。这个功能我会，我可以帮您吗？”"}],correctAnswer:"c",feedback:["✨ 会称呼，是尊重。","✨ 会帮助，是本领。","✨ 不炫耀，是谦虚。"],resolution:["小乐用合适的称呼问好，也谦虚地帮助张老师。"],learningText:"称尊长，勿呼名；对尊长，勿见能。"}
];

window.CHAPTERS = {
  1:{completeTitle:"🎉 第一关完成！",summaryTitle:"👀 我们学会了：认一认",points:["他是我的长辈或师长吗？","我应该怎样称呼他？"],button:"进入下一章"},
  2:{intro:["知道尊长的名字，就可以直接叫名字吗？","不一定！","勿呼名！","称呼也表达我们的关系和尊重。"],completeTitle:"第二关完成！",summaryTitle:"🙋 我们学会了：称一称",points:["知道名字，不等于直接叫名字。","不知道称呼，可以有礼貌地请教。"],after:["称尊长，勿呼名。"]},
  3:{intro:["有本领是一件好事。","可是……有本领就要一直炫耀吗？","🌱 有能力，也要谦一谦"],completeTitle:"第三关完成！",summaryTitle:"🌱 我们学会了：谦一谦",points:["会做，不嘲笑","懂得，不炫耀","有能力，用来帮助别人"],after:["已经收集9颗礼仪之心！","还剩最后3颗！"]}
};
